import { useMemo, useState } from 'react'
import Topbar from '../components/Topbar'
import DataTable from '../components/DataTable'
import { useRealtimeTable } from '../hooks/useRealtimeTable'
import { supabase } from '../lib/supabase'
import { useToast } from '../components/Toast'
import { formatMoney, formatNumber } from '../utils/format'

export default function AbuseFlags() {
  const { showToast } = useToast(); const [search, setSearch] = useState(''); const [busy, setBusy] = useState(false)
  const table = useRealtimeTable({ key: ['abuse-flags'], queryFn: async () => supabase.rpc('abuse_flags_list'), intervalMs: 15000 })
  const rows = useMemo(() => (table.data || []).filter((row) => !search || [row.sender_number, row.reason, row.status].join(' ').toLowerCase().includes(search.toLowerCase())), [table.data, search])
  async function rescan() { setBusy(true); const { data, error } = await supabase.rpc('scan_abuse_patterns', { p_min_declines: 3, p_days: 7 }); setBusy(false); showToast(error ? `Scan failed: ${error.message}` : `Scan complete: ${data?.flagged_count || 0} flagged`, error ? 'error' : 'success'); table.refresh() }
  async function clear(row) { if (!window.confirm(`Mark ${row.sender_number} as cleared?`)) return; const { error } = await supabase.rpc('abuse_flag_clear', { p_id: row.id }); showToast(error ? error.message : 'Flag cleared', error ? 'error' : 'success'); table.refresh() }
  async function promote(row) { const typed = window.prompt(`Type the phone number to confirm blacklist: ${row.sender_number}`); if (typed !== row.sender_number) return; const { error } = await supabase.rpc('abuse_flag_promote_to_blacklist', { p_id: row.id, p_reason: null }); showToast(error ? error.message : 'Added to blacklist', error ? 'error' : 'success'); table.refresh() }
  const columns = [{ key: 'sender_number', label: 'Phone', render: (row) => <span className="font-mono font-bold text-gold">{row.sender_number || '—'}</span> }, { key: 'declined_no_evidence_count', label: 'Declined no evidence', render: (row) => <b className="text-danger">{row.declined_no_evidence_count ?? 0}</b> }, { key: 'total_declined_amount', label: 'Amount', render: (row) => formatMoney(row.total_declined_amount) }, { key: 'reason', label: 'Reason', render: (row) => <span className="block max-w-[360px] truncate" title={row.reason}>{row.reason || '—'}</span> }, { key: 'status', label: 'Status', render: (row) => <span className={`rounded-full px-2 py-1 text-xs font-bold ${row.status === 'blacklisted' ? 'bg-danger/15 text-danger' : row.status === 'cleared' ? 'bg-success/15 text-success' : 'bg-warning/15 text-warning'}`}>{row.status === 'blacklisted' ? '🚫 Blacklisted' : row.status === 'cleared' ? '✅ Cleared' : '⚠️ Flagged'}</span> }, { key: 'actions', label: 'Actions', render: (row) => row.status === 'flagged' ? <div className="flex gap-2"><button disabled={busy} onClick={(event) => { event.stopPropagation(); promote(row) }} className="rounded-lg bg-danger px-2 py-1 text-xs font-bold text-white">Blacklist</button><button disabled={busy} onClick={(event) => { event.stopPropagation(); clear(row) }} className="rounded-lg border border-border px-2 py-1 text-xs font-bold text-text">Clear</button></div> : '—' }]
  return <div className="flex h-full flex-col bg-bg"><Topbar title="🚩 Abuse Flags" subtitle="Suspicious clients detected by failed or unsupported transactions" onRefresh={table.refresh} isFetching={table.isFetching} /><div className="flex-1 space-y-5 overflow-y-auto p-4 md:p-6"><div className="mx-auto max-w-[1500px] space-y-5"><div className="grid grid-cols-2 gap-3 md:grid-cols-4"><Stat label="Flagged" value={rows.filter((row) => row.status === 'flagged').length} tone="text-warning" /><Stat label="Blacklisted" value={rows.filter((row) => row.status === 'blacklisted').length} tone="text-danger" /><Stat label="Cleared" value={rows.filter((row) => row.status === 'cleared').length} tone="text-success" /><Stat label="Total" value={rows.length} /></div><div className="flex flex-wrap gap-3 rounded-2xl border border-border bg-card p-4"><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search phone or reason..." className="min-w-[260px] flex-1 rounded-lg border border-border bg-surface px-3 py-2 text-sm text-text" /><button disabled={busy} onClick={rescan} className="rounded-lg bg-gold px-4 py-2 text-sm font-bold text-bg">🔍 Rescan last 7 days</button></div><DataTable columns={columns} data={rows} loading={table.isLoading} error={table.error} emptyEmoji="🚩" emptyTitle="No abuse flags" emptySubtitle="Run a scan to detect suspicious patterns" /></div></div></div>
}
function Stat({ label, value, tone = 'text-gold' }) { return <div className="rounded-xl border border-border bg-card p-4"><div className="text-xs text-muted">{label}</div><div className={`mt-2 text-2xl font-black ${tone}`}>{formatNumber(value)}</div></div> }
