import { useEffect, useMemo, useState } from 'react'
import { useRealtimeTable } from '../hooks/useRealtimeTable'
import { formatMoney, formatNumber, formatRelativeTime, formatAbsoluteDate } from '../utils/format'

function statusTone(status) {
  if (status === 'PAID' || status === 'completed') return 'text-success'
  if (status === 'DECLINED' || status === 'failed') return 'text-danger'
  return 'text-warning'
}

function Panel({ title, eyebrow, children, className = '' }) {
  return <section className={`rounded-3xl border border-border bg-card/80 p-5 shadow-lg shadow-slate-950/5 ${className}`}><div className="mb-4 flex items-end justify-between gap-3"><div><div className="text-[10px] font-black uppercase tracking-[0.22em] text-gold">{eyebrow}</div><h2 className="mt-1 text-lg font-extrabold text-text">{title}</h2></div><span className="h-2 w-2 rounded-full bg-success shadow-[0_0_14px_var(--color-success)]" /></div>{children}</section>
}

export default function AutomationTV() {
  const [now, setNow] = useState(new Date())
  const transactions = useRealtimeTable({ key: ['automation-tv-transactions'], queryFn: async (sb) => sb.from('maven_transactions').select('tx_id, amount, status, sender_name, sender_number, payment_method, created_utc, updated_at').order('updated_at', { ascending: false }).limit(80), intervalMs: 10000 })
  const sms = useRealtimeTable({ key: ['automation-tv-sms'], queryFn: async (sb) => sb.from('inbound_sms').select('id, amount, sms_category, sender_name, sender_number, received_at, matched, match_status, consumed_by_tx_id, matched_transaction_id, maven_transaction_id').order('received_at', { ascending: false }).limit(80), intervalMs: 10000 })
  const jobs = useRealtimeTable({ key: ['automation-tv-jobs'], queryFn: async (sb) => sb.from('browser_jobs').select('id, tx_id, target_status, state, source, created_at, updated_at, completed_at').order('updated_at', { ascending: false }).limit(80), intervalMs: 10000 })

  useEffect(() => { const timer = setInterval(() => setNow(new Date()), 1000); return () => clearInterval(timer) }, [])

  const txRows = useMemo(() => transactions.data || [], [transactions.data])
  const smsRows = useMemo(() => sms.data || [], [sms.data])
  const jobRows = useMemo(() => jobs.data || [], [jobs.data])
  const stats = useMemo(() => {
    const today = new Date(); today.setHours(0, 0, 0, 0)
    const todayTx = txRows.filter((row) => new Date(row.created_utc || 0) >= today)
    const matched = smsRows.filter((row) => row.matched || row.match_status || row.consumed_by_tx_id || row.matched_transaction_id || row.maven_transaction_id).length
    return { today: todayTx.length, volume: todayTx.reduce((sum, row) => sum + Number(row.amount || 0), 0), paid: todayTx.filter((row) => row.status === 'PAID').length, pending: todayTx.filter((row) => row.status === 'PENDING').length, declined: todayTx.filter((row) => row.status === 'DECLINED').length, matched, running: jobRows.filter((row) => row.state === 'running').length, queued: jobRows.filter((row) => row.state === 'pending').length }
  }, [txRows, smsRows, jobRows])

  const latestJobs = jobRows.slice(0, 7)
  const latestTransactions = txRows.slice(0, 8)
  const latestSms = smsRows.slice(0, 8)
  const successRate = stats.today ? Math.round((stats.paid / stats.today) * 100) : 0

  return <div className="h-full overflow-y-auto bg-bg p-4 text-text md:p-6 xl:p-8"><div className="mx-auto max-w-[1800px] space-y-5">
    <header className="flex flex-wrap items-end justify-between gap-4 rounded-3xl border border-gold/25 bg-gradient-to-br from-gold/15 via-card to-card p-6 shadow-xl shadow-gold/5"><div><div className="mb-2 flex items-center gap-3"><span className="relative flex h-3 w-3"><span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-success opacity-75" /><span className="relative inline-flex h-3 w-3 rounded-full bg-success" /></span><span className="text-xs font-black uppercase tracking-[0.3em] text-success">Live automation theater</span></div><h1 className="text-3xl font-black tracking-tight md:text-5xl">Monitor Process TV</h1><p className="mt-2 max-w-2xl text-sm text-muted md:text-base">مراقبة مباشرة لمسار العملية: استقبال البيانات، المطابقة، القرار، ثم التنفيذ الآلي.</p></div><div className="text-left md:text-right"><div className="font-mono text-3xl font-black text-gold">{now.toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit', second: '2-digit', timeZone: 'Africa/Cairo' })}</div><div className="mt-1 text-xs text-muted">Cairo · {now.toLocaleDateString('en-GB', { weekday: 'long', day: '2-digit', month: 'short', timeZone: 'Africa/Cairo' })}</div><div className="mt-3 text-xs font-bold text-success">● AUTO REFRESH 10s</div></div></header>

    <div className="grid grid-cols-2 gap-3 md:grid-cols-4 xl:grid-cols-7">{[['Today transactions', formatNumber(stats.today), '📊', 'text-gold'], ['Volume', formatMoney(stats.volume), '💰', 'text-gold'], ['Success rate', `${successRate}%`, '✅', 'text-success'], ['Pending', formatNumber(stats.pending), '⏳', 'text-warning'], ['Declined', formatNumber(stats.declined), '⛔', 'text-danger'], ['SMS matched', formatNumber(stats.matched), '📨', 'text-violet-500'], ['Jobs running', formatNumber(stats.running), '⚙️', 'text-blue-500']].map(([label, value, icon, tone]) => <div key={label} className="rounded-2xl border border-border bg-card p-4"><div className="flex items-center justify-between text-xs text-muted"><span>{label}</span><span>{icon}</span></div><div className={`mt-2 truncate text-2xl font-black ${tone}`}>{value}</div></div>)}</div>

    <div className="grid gap-5 xl:grid-cols-[1.4fr_1fr]"><Panel title="Automation pipeline" eyebrow="Process flow" className="min-h-[270px]"><div className="grid gap-3 md:grid-cols-4">{[['01', 'INGEST', 'SMS + Maven events', smsRows.length, '📡', 'text-blue-500'], ['02', 'MATCH', 'Rules + AI signals', stats.matched, '🧩', 'text-violet-500'], ['03', 'DECIDE', 'Paid / pending / declined', stats.paid + stats.pending + stats.declined, '🧠', 'text-gold'], ['04', 'EXECUTE', 'Browser jobs', stats.running + stats.queued, '⚡', 'text-success']].map(([step, name, sub, value, icon, tone], index) => <div key={name} className="relative rounded-2xl border border-border bg-surface p-4"><div className="flex items-center justify-between"><span className="font-mono text-xs font-bold text-muted">{step}</span><span className="text-xl">{icon}</span></div><div className={`mt-5 text-sm font-black tracking-widest ${tone}`}>{name}</div><div className="mt-1 text-xs text-muted">{sub}</div><div className="mt-4 text-2xl font-black text-text">{formatNumber(value)}</div>{index < 3 && <span className="absolute -right-3 top-1/2 z-10 hidden text-xl text-gold md:block">›</span>}</div>)}</div><div className="mt-5 flex items-center justify-between rounded-xl border border-border bg-surface px-4 py-3 text-xs"><span className="text-muted">Queue state</span><span className="font-bold text-success">{stats.queued ? `${stats.queued} jobs waiting` : 'Clear · all systems flowing'}</span></div></Panel>
      <Panel title="Execution activity" eyebrow="Browser worker"><div className="space-y-2">{latestJobs.length ? latestJobs.map((job) => <div key={job.id} className="flex items-center gap-3 rounded-xl bg-surface px-3 py-2.5"><span className={`h-2.5 w-2.5 shrink-0 rounded-full ${job.state === 'completed' ? 'bg-success' : job.state === 'failed' ? 'bg-danger' : 'bg-warning animate-pulse'}`} /><div className="min-w-0 flex-1"><div className="truncate text-sm font-bold text-text">TX #{job.tx_id} · {job.target_status || '—'}</div><div className="text-[11px] text-muted">{job.source || 'automation'} · {formatRelativeTime(job.updated_at || job.created_at)}</div></div><span className={`text-xs font-bold uppercase ${statusTone(job.state)}`}>{job.state}</span></div>) : <div className="py-10 text-center text-sm text-muted">No automation jobs yet</div>}</div></Panel></div>

    <div className="grid gap-5 xl:grid-cols-2"><Panel title="Live transactions" eyebrow="Maven stream"><div className="overflow-hidden rounded-xl border border-border"><table className="w-full text-sm"><thead className="bg-surface text-xs text-muted"><tr><th className="px-3 py-3 text-left">TX</th><th className="px-3 py-3 text-left">Customer</th><th className="px-3 py-3 text-left">Amount</th><th className="px-3 py-3 text-left">Status</th><th className="px-3 py-3 text-left">Updated</th></tr></thead><tbody>{latestTransactions.map((row) => <tr key={row.tx_id} className="border-t border-border"><td className="px-3 py-3 font-mono font-bold text-gold">#{row.tx_id}</td><td className="max-w-[150px] truncate px-3 py-3">{row.sender_name || row.sender_number || 'Unknown'}</td><td className="px-3 py-3 font-bold">{formatMoney(row.amount)}</td><td className={`px-3 py-3 font-bold ${statusTone(row.status)}`}>{row.status}</td><td className="px-3 py-3 text-xs text-muted">{formatRelativeTime(row.updated_at || row.created_utc)}</td></tr>)}</tbody></table></div></Panel>
      <Panel title="SMS matching radar" eyebrow="Incoming signals"><div className="space-y-2">{latestSms.length ? latestSms.map((row) => { const linked = row.consumed_by_tx_id || row.matched_transaction_id || row.maven_transaction_id; return <div key={row.id} className="flex items-center gap-3 rounded-xl border border-border bg-surface px-3 py-3"><span className="text-xl">{row.sms_category === 'withdrawal' ? '📤' : '📥'}</span><div className="min-w-0 flex-1"><div className="flex items-center gap-2 text-sm font-bold"><span className="truncate">{row.sender_name || row.sender_number || 'Unknown sender'}</span>{linked ? <span className="rounded-full bg-success/15 px-2 py-0.5 text-[10px] text-success">LINKED #{linked}</span> : <span className="rounded-full bg-warning/15 px-2 py-0.5 text-[10px] text-warning">UNMATCHED</span>}</div><div className="text-xs text-muted">{formatMoney(row.amount)} · {formatAbsoluteDate(row.received_at)}</div></div><span className="text-xs font-bold text-muted">#{row.id}</span></div> }) : <div className="py-10 text-center text-sm text-muted">No SMS signals yet</div>}</div></Panel></div>
  </div></div>
}
