import { useMemo, useState } from 'react'
import { useParams } from 'react-router-dom'
import { useRealtimeTable } from '../hooks/useRealtimeTable'
import { supabase } from '../lib/supabase'
import Topbar from '../components/Topbar'
import { BarChart3, Calculator, CreditCard, DollarSign, Settings2, WalletCards } from 'lucide-react'

const DEFAULT_CHANNELS = [
  { id: 'instapay', name: 'InstaPay', fixed: 2, rate: 1.5, min: 1, max: 500, active: true },
  { id: 'vodafone', name: 'Vodafone Cash', fixed: 3, rate: 2, min: 2, max: 400, active: true },
  { id: 'orange', name: 'Orange Cash', fixed: 3, rate: 2, min: 2, max: 400, active: true },
  { id: 'etisalat', name: 'Etisalat Cash', fixed: 3, rate: 2, min: 2, max: 400, active: true },
  { id: 'fawry', name: 'Fawry', fixed: 5, rate: 1, min: 5, max: 300, active: true },
  { id: 'bank', name: 'Bank Transfer', fixed: 10, rate: .5, min: 10, max: 1000, active: true },
  { id: 'meeza', name: 'Meeza', fixed: 2, rate: 1.5, min: 1, max: 500, active: true },
  { id: 'ewallet', name: 'E-Wallet', fixed: 2, rate: 1.8, min: 1, max: 450, active: true },
]
const money = (value) => `${Number(value || 0).toLocaleString('en-EG', { maximumFractionDigits: 0 })} EGP`
const pct = (value) => `${Number(value || 0).toFixed(2)}%`

export default function ExecutiveDashboard() {
  const { tab: routeTab } = useParams()
  const tab = ['overview', 'channels', 'fees', 'calculator'].includes(routeTab) ? routeTab : 'overview'
  const [channels, setChannels] = useState(() => JSON.parse(localStorage.getItem('press2pay-fee-channels') || 'null') || DEFAULT_CHANNELS)
  const [amount, setAmount] = useState(1000)
  const [platformRate, setPlatformRate] = useState(0.3)
  const [search, setSearch] = useState('')
  const tx = useRealtimeTable({ key: ['executive-dashboard-transactions'], queryFn: async (sb) => sb.from('maven_transactions').select('tx_id, amount, status, payment_method, master_merchant, merchant, sub_merchant, created_utc').order('created_utc', { ascending: false }).limit(2000), intervalMs: 30000 })
  const transactions = tx.data || []
  const filtered = transactions.filter((row) => !search || JSON.stringify(row).toLowerCase().includes(search.toLowerCase()))
  const stats = useMemo(() => {
    const paid = filtered.filter((row) => ['PAID', 'APPROVED', 'COMPLETED', 'SUCCEEDED'].includes(String(row.status).toUpperCase()))
    const volume = paid.reduce((sum, row) => sum + Number(row.amount || 0), 0)
    const methods = new Set(paid.map((row) => row.payment_method).filter(Boolean)).size
    return { paid: paid.length, volume, success: filtered.length ? paid.length / filtered.length * 100 : 0, methods }
  }, [filtered])

  function updateChannel(id, key, value) {
    const next = channels.map((channel) => channel.id === id ? { ...channel, [key]: key === 'active' ? value : Number(value) } : channel)
    setChannels(next); localStorage.setItem('press2pay-fee-channels', JSON.stringify(next))
  }

  const selected = channels.find((channel) => channel.id === 'instapay') || channels[0]
  const channelFee = selected ? Math.min(Math.max(selected.fixed + amount * selected.rate / 100, selected.min), selected.max) : 0
  const platformFee = amount * platformRate / 100
  const navigation = [['overview', 'Overview', BarChart3], ['channels', 'Payment Channels', CreditCard], ['fees', 'Fee Settings', Settings2], ['calculator', 'Fee Calculator', Calculator]]

  return <div className="flex h-full flex-col bg-bg"><Topbar title="MZ Groups Management Dashboard" subtitle="Payment operations, channel fees and merchant performance" onRefresh={tx.refresh} isFetching={tx.isFetching} /><div className="flex items-center gap-2 overflow-x-auto border-b border-border bg-surface px-4 py-2">{navigation.map(([key, label, Icon]) => <a key={key} href={`/executive-dashboard/${key}`} className={`flex shrink-0 items-center gap-2 rounded-lg px-3 py-2 text-sm font-semibold ${tab === key ? 'bg-gold/15 text-gold' : 'text-muted hover:bg-card hover:text-text'}`}><Icon size={15} />{label}</a>)}</div><main className="flex-1 space-y-6 overflow-y-auto p-4 md:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-gold">Executive view</p><h1 className="mt-1 text-2xl font-bold text-text">{tab === 'overview' ? 'Business overview' : tab === 'channels' ? 'Payment channels' : tab === 'fees' ? 'Fee configuration' : 'Fee impact calculator'}</h1></div><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search transaction, merchant..." className="w-full max-w-xs rounded-lg border border-border bg-card px-3 py-2 text-sm text-text outline-none focus:border-gold" /></div>
    {tab === 'overview' && <><div className="grid grid-cols-2 gap-4 lg:grid-cols-4"><Kpi icon={DollarSign} label="Paid volume" value={money(stats.volume)} tone="gold" note={`${stats.paid.toLocaleString()} paid transactions`} /><Kpi icon={BarChart3} label="Success rate" value={pct(stats.success)} tone="green" note={`${filtered.length.toLocaleString()} transactions`} /><Kpi icon={CreditCard} label="Active methods" value={stats.methods} tone="blue" note="from live Maven data" /><Kpi icon={WalletCards} label="Live records" value={transactions.length.toLocaleString()} tone="purple" note="auto-refresh 30s" /></div><section className="rounded-2xl border border-border bg-card p-5"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-bold text-text">Payment channel performance</h2><p className="mt-1 text-xs text-muted">Current fee configuration and recent usage</p></div><a href="/executive-dashboard/channels" className="text-xs font-bold text-gold">Manage channels →</a></div><ChannelTable channels={channels.slice(0, 6)} compact /></section><section className="rounded-2xl border border-border bg-card p-5"><h2 className="mb-4 font-bold text-text">Merchant distribution</h2><MerchantSummary rows={filtered} /></section></>}
    {tab === 'channels' && <section className="rounded-2xl border border-border bg-card p-5"><SectionHead title="Pay-In channels" subtitle="Enable channels and manage their fixed and percentage fee rules." /><ChannelTable channels={channels} updateChannel={updateChannel} /></section>}
    {tab === 'fees' && <section className="grid gap-5 lg:grid-cols-2"><FeePanel title="Platform fees" fields={[["Platform fixed fee (EGP)", 5], ["Platform rate (%)", platformRate]]} onRate={setPlatformRate} /><FeePanel title="Settlement fees" fields={[["Bank transfer fixed fee", 25], ["Settlement rate (%)", .3], ["USDT FX markup (%)", .2]]} /><section className="rounded-2xl border border-border bg-card p-5 lg:col-span-2"><SectionHead title="Per-company fees" subtitle="Company overrides can be applied from the merchant payment setup route." /><MerchantSummary rows={filtered} /></section></section>}
    {tab === 'calculator' && <section className="grid gap-5 lg:grid-cols-[minmax(0,420px)_1fr]"><div className="rounded-2xl border border-border bg-card p-5"><SectionHead title="Fee impact calculator" subtitle="Estimate customer, platform and net amounts." /><label className="mt-5 block text-sm text-muted">Transaction amount (EGP)<input type="number" min="0" value={amount} onChange={(event) => setAmount(Number(event.target.value))} className="mt-2 w-full rounded-lg border border-border bg-surface px-3 py-2 text-lg font-bold text-text" /></label><label className="mt-4 block text-sm text-muted">Platform rate (%)<input type="number" step=".1" value={platformRate} onChange={(event) => setPlatformRate(Number(event.target.value))} className="mt-2 w-full rounded-lg border border-border bg-surface px-3 py-2 text-text" /></label></div><div className="rounded-2xl border border-border bg-card p-5"><SectionHead title="Estimate" subtitle={`Using ${selected?.name || 'payment channel'}`} /><div className="mt-5 space-y-3"><Result label="Transaction amount" value={money(amount)} /><Result label="Payment channel fee" value={money(channelFee)} tone="gold" /><Result label="Platform fee" value={money(platformFee)} tone="red" /><Result label="Net after fees" value={money(Math.max(0, amount - channelFee - platformFee))} tone="green" /></div></div></section>}
    {tab !== 'calculator' && <section className="rounded-2xl border border-border bg-card p-5"><SectionHead title="Latest transactions" subtitle={`${filtered.length} records`} /><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[800px] text-sm"><thead className="bg-surface text-xs text-muted"><tr>{['ID', 'Master merchant', 'Sub-merchant', 'Method', 'Amount', 'Status'].map((head) => <th key={head} className="px-3 py-3 text-right">{head}</th>)}</tr></thead><tbody>{filtered.slice(0, 20).map((row) => <tr key={row.tx_id} className="border-t border-border"><td className="px-3 py-3 font-mono text-gold">{row.tx_id}</td><td className="px-3 py-3">{row.master_merchant || '—'}</td><td className="px-3 py-3">{row.sub_merchant || row.merchant || '—'}</td><td className="px-3 py-3">{row.payment_method || '—'}</td><td className="px-3 py-3 font-mono">{money(row.amount)}</td><td className="px-3 py-3"><span className={`rounded-full px-2 py-1 text-xs font-bold ${['PAID', 'APPROVED'].includes(String(row.status).toUpperCase()) ? 'bg-success/15 text-success' : 'bg-surface text-muted'}`}>{row.status || '—'}</span></td></tr>)}</tbody></table></div></section>}
  </main></div>
}

function Kpi({ icon: Icon, label, value, tone, note }) { return <div className="rounded-2xl border border-border bg-card p-4"><div className="flex items-center gap-2 text-xs text-muted"><Icon size={15} />{label}</div><div className={`mt-2 text-2xl font-bold text-${tone}`}>{value}</div><div className="mt-1 text-xs text-muted">{note}</div></div> }
function SectionHead({ title, subtitle }) { return <div><h2 className="font-bold text-text">{title}</h2><p className="mt-1 text-xs text-muted">{subtitle}</p></div> }
function Result({ label, value, tone = 'text-text' }) { return <div className="flex items-center justify-between rounded-xl bg-surface px-4 py-3"><span className="text-sm text-muted">{label}</span><strong className={`font-mono ${tone}`}>{value}</strong></div> }
function FeePanel({ title, fields, onRate }) { return <section className="rounded-2xl border border-border bg-card p-5"><SectionHead title={title} subtitle="Configuration is saved for this dashboard session." /><div className="mt-5 grid gap-3 sm:grid-cols-2">{fields.map(([label, value]) => <label key={label} className="text-xs text-muted">{label}<input type="number" step=".1" value={value} onChange={(event) => label.toLowerCase().includes('rate') && onRate?.(Number(event.target.value))} className="mt-1 w-full rounded-lg border border-border bg-surface px-3 py-2 text-sm text-text" /></label>)}</div></section> }
function ChannelTable({ channels, updateChannel, compact = false }) { return <div className="mt-4 overflow-x-auto"><table className="w-full min-w-[720px] text-sm"><thead className="bg-surface text-xs text-muted"><tr>{['Channel', 'Fixed (EGP)', 'Rate (%)', 'Min', 'Max', 'Status'].map((head) => <th key={head} className="px-3 py-3 text-right">{head}</th>)}</tr></thead><tbody>{channels.map((channel) => <tr key={channel.id} className="border-t border-border"><td className="px-3 py-3 font-semibold">{channel.name}</td>{['fixed', 'rate', 'min', 'max'].map((key) => <td key={key} className="px-3 py-3">{updateChannel && !compact ? <input type="number" step=".1" value={channel[key]} onChange={(event) => updateChannel(channel.id, key, event.target.value)} className="w-24 rounded border border-border bg-surface px-2 py-1 text-sm text-text" /> : channel[key]}</td>)}<td className="px-3 py-3">{updateChannel && !compact ? <button onClick={() => updateChannel(channel.id, 'active', !channel.active)} className={`rounded-full px-2 py-1 text-xs font-bold ${channel.active ? 'bg-success/15 text-success' : 'bg-danger/15 text-danger'}`}>{channel.active ? 'Active' : 'Disabled'}</button> : <span className="text-success">● Active</span>}</td></tr>)}</tbody></table></div> }
function MerchantSummary({ rows }) { const groups = [...rows.reduce((map, row) => { const key = row.master_merchant || 'Unknown'; const current = map.get(key) || { name: key, count: 0, volume: 0 }; current.count += 1; current.volume += Number(row.amount || 0); map.set(key, current); return map }, new Map()).values()]; return <div className="grid gap-2 md:grid-cols-2">{groups.slice(0, 8).map((group) => <div key={group.name} className="flex items-center justify-between rounded-xl bg-surface px-4 py-3"><span className="font-semibold text-text">{group.name}</span><span className="text-right text-xs text-muted">{group.count} tx · <b className="font-mono text-gold">{money(group.volume)}</b></span></div>)}{!groups.length && <span className="text-sm text-muted">No merchant data available.</span>}</div> }
