import { useMemo } from 'react'
import Topbar from '../components/Topbar'
import { useRealtimeTable } from '../hooks/useRealtimeTable'
import { formatAbsoluteDate, formatNumber } from '../utils/format'

const time = (row, keys) => { const key = keys.find((name) => row?.[name]); return key ? new Date(row[key]).getTime() : null }

export default function HealthV2() {
  const settings = useRealtimeTable({ key: ['health-v2-settings'], queryFn: async (sb) => sb.from('automation_settings').select('*').eq('id', 1).limit(1), intervalMs: 15000 })
  const jobs = useRealtimeTable({ key: ['health-v2-jobs'], queryFn: async (sb) => sb.from('browser_jobs').select('*').order('updated_at', { ascending: false }).limit(500), intervalMs: 10000 })
  const reviews = useRealtimeTable({ key: ['health-v2-reviews'], queryFn: async (sb) => sb.from('review_queue').select('*').order('created_at', { ascending: false }).limit(1000), intervalMs: 10000 })
  const payouts = useRealtimeTable({ key: ['health-v2-payouts'], queryFn: async (sb) => sb.from('transactions').select('*').eq('trx_type', 'withdrawal').order('created_at', { ascending: false }).limit(1000), intervalMs: 10000 })
  const jobRows = jobs.data || []; const reviewRows = reviews.data || []; const payoutRows = payouts.data || []; const setting = settings.data?.[0] || {}
  const running = jobRows.filter((row) => ['running', 'processing', 'started'].includes(String(row.state || row.status).toLowerCase())).length; const pending = jobRows.filter((row) => ['pending', 'queued', 'waiting'].includes(String(row.state || row.status).toLowerCase())).length; const failed = jobRows.filter((row) => ['failed', 'error'].includes(String(row.state || row.status).toLowerCase())).length
  const approvalMinutes = useMemo(() => { const values = payoutRows.map((row) => { const start = time(row, ['created_at', 'created_utc']); const end = time(row, ['approved_at', 'decided_at', 'completed_at', 'updated_at']); return start && end && end >= start ? (end - start) / 60000 : null }).filter(Boolean); return values.length ? values.reduce((sum, value) => sum + value, 0) / values.length : null }, [payoutRows])
  const conversion = payoutRows.length ? payoutRows.filter((row) => ['completed', 'paid', 'PAID'].includes(row.status)).length / payoutRows.length * 100 : 0
  const refresh = () => { settings.refresh(); jobs.refresh(); reviews.refresh(); payouts.refresh() }
  return <div className="flex h-full flex-col bg-bg"><Topbar title="System & Automation Health" subtitle="Speed, execution, approval time and conversion" onRefresh={refresh} isFetching={settings.isFetching || jobs.isFetching || reviews.isFetching || payouts.isFetching} /><div className="flex-1 overflow-y-auto p-4 md:p-6"><div className="mx-auto max-w-[1600px] space-y-5"><div className="grid grid-cols-2 gap-3 md:grid-cols-7"><Stat label="Running" value={running} /><Stat label="Pending" value={pending} /><Stat label="Failed" value={failed} tone="text-danger" /><Stat label="Avg approval" value={approvalMinutes == null ? '—' : `${approvalMinutes.toFixed(1)} min`} tone="text-blue-400" /><Stat label="Conversion rate" value={`${conversion.toFixed(1)}%`} tone="text-success" /><Stat label="Payout requests" value={payoutRows.length} /><Stat label="Last check" value={formatAbsoluteDate(new Date())} /></div><div className="grid gap-4 md:grid-cols-3"><Card title="⚡ Automation speed" ok={!jobs.error && failed === 0}><Line label="Average approval time" value={approvalMinutes == null ? 'No timing data' : `${approvalMinutes.toFixed(1)} minutes`} /><Line label="Queue execution" value={`${running} running · ${pending} pending`} /><Line label="Failed jobs" value={formatNumber(failed)} /></Card><Card title="📈 Conversion" ok={!payouts.error}><Line label="Completed / total" value={`${payoutRows.filter((row) => ['completed', 'paid', 'PAID'].includes(row.status)).length} / ${payoutRows.length}`} /><Line label="Conversion rate" value={`${conversion.toFixed(1)}%`} /><Line label="Rejected" value={formatNumber(payoutRows.filter((row) => ['rejected', 'DECLINED'].includes(row.status)).length)} /></Card><Card title="✅ Approvals" ok={!reviews.error}><Line label="Review decisions" value={formatNumber(reviewRows.length)} /><Line label="Automation" value={setting.automation_enabled === false ? 'Disabled' : 'Enabled'} /><Line label="Gateway queue" value={payouts.error ? 'Connection error' : 'Connected'} /></Card></div><Card title="🧾 Recent execution jobs" ok={failed === 0}><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-xs"><thead className="text-left text-muted"><tr><th className="p-2">ID</th><th className="p-2">TX</th><th className="p-2">State</th><th className="p-2">Updated</th></tr></thead><tbody>{jobRows.slice(0, 30).map((row) => <tr key={row.id} className="border-t border-border"><td className="p-2 font-mono">{row.id}</td><td className="p-2 font-mono text-gold">{row.tx_id || '—'}</td><td className="p-2">{row.state || row.status || '—'}</td><td className="p-2 text-muted">{formatAbsoluteDate(row.updated_at || row.completed_at || row.created_at)}</td></tr>)}</tbody></table></div></Card></div></div></div>
}
function Card({ title, ok, children }) { return <section className="rounded-2xl border border-border bg-card p-5"><div className="flex items-center justify-between"><h2 className="font-black text-text">{title}</h2><span className={`rounded-full px-3 py-1 text-xs font-bold ${ok ? 'bg-success/15 text-success' : 'bg-danger/15 text-danger'}`}>{ok ? 'Healthy' : 'Needs review'}</span></div><div className="mt-4 space-y-2">{children}</div></section> }
function Line({ label, value }) { return <div className="flex justify-between gap-3 border-b border-border py-2 text-sm last:border-0"><span className="text-muted">{label}</span><b className="text-text">{value}</b></div> }
function Stat({ label, value, tone = 'text-gold' }) { return <div className="rounded-xl border border-border bg-card p-4"><div className="text-xs text-muted">{label}</div><div className={`mt-2 truncate text-xl font-black ${tone}`}>{value}</div></div> }
