import { useMemo } from 'react'
import { useRealtimeTable } from '../hooks/useRealtimeTable'
import Topbar from '../components/Topbar'
import { formatAbsoluteDate, formatNumber } from '../utils/format'

function HealthCard({ title, status, children }) { return <section className="rounded-2xl border border-border bg-card p-5"><div className="flex items-center justify-between gap-3"><h2 className="font-black text-text">{title}</h2><span className={`rounded-full px-3 py-1 text-xs font-bold ${status ? 'bg-success/15 text-success' : 'bg-danger/15 text-danger'}`}>{status ? 'سليم' : 'يحتاج مراجعة'}</span></div><div className="mt-4 space-y-2 text-sm text-muted">{children}</div></section> }

export default function Health() {
  const settings = useRealtimeTable({ key: ['health-settings'], queryFn: async (sb) => sb.from('automation_settings').select('*').eq('id', 1).limit(1), intervalMs: 15000 })
  const jobs = useRealtimeTable({ key: ['health-jobs'], queryFn: async (sb) => sb.from('browser_jobs').select('id,state,priority,next_run_at,updated_at').order('updated_at', { ascending: false }).limit(500), intervalMs: 10000 })
  const telegram = useRealtimeTable({ key: ['health-telegram'], queryFn: async (sb) => sb.from('telegram_config').select('*').limit(1), intervalMs: 30000 })
  const setting = settings.data?.[0] || {}; const jobRows = jobs.data || []; const running = jobRows.filter((row) => row.state === 'running').length; const pending = jobRows.filter((row) => row.state === 'pending').length; const failed = jobRows.filter((row) => ['failed', 'error'].includes(String(row.state).toLowerCase())).length
  const automationHealthy = setting.automation_enabled !== false && failed === 0; const backendHealthy = !settings.error && !jobs.error; const checks = useMemo(() => ({ running, pending, failed }), [running, pending, failed])
  return <div className="flex h-full flex-col bg-bg"><Topbar title="🩺 صحة النظام والأتمتة" subtitle="مراقبة Backend وSupabase وBrowser Worker" onRefresh={() => { settings.refresh(); jobs.refresh(); telegram.refresh() }} isFetching={settings.isFetching || jobs.isFetching} /><div className="flex-1 overflow-y-auto p-4 md:p-6"><div className="mx-auto max-w-[1500px] space-y-5"><div className="grid grid-cols-2 gap-3 md:grid-cols-4">{[['Jobs شغالة', checks.running], ['Jobs معلقة', checks.pending], ['Jobs فاشلة', checks.failed], ['آخر فحص', formatAbsoluteDate(new Date())].map(([label, value]) => <div key={label} className="rounded-xl border border-border bg-card p-4"><div className="text-xs text-muted">{label}</div><div className="mt-2 truncate text-xl font-black text-gold">{typeof value === 'number' ? formatNumber(value) : value}</div></div>)}</div><div className="grid gap-4 md:grid-cols-2"><HealthCard title="⚙️ الأتمتة" status={automationHealthy}><div>Automation: <b className="text-text">{setting.automation_enabled === false ? 'متوقفة' : 'مفعّلة'}</b></div><div>Maven: <b className="text-text">{setting.maven_enabled === false ? 'متوقف' : 'مفعّل'}</b></div><div>Turbo: <b className="text-text">{setting.turbo_mode ? 'مفعّل' : 'متوقف'}</b></div><div>حد الرفض: <b className="text-text">{setting.decline_grace_minutes || 0} دقيقة</b></div></HealthCard><HealthCard title="🔌 Backend / Supabase" status={backendHealthy}><div>Data API: <b className="text-text">{settings.error ? 'خطأ اتصال' : 'متصل'}</b></div><div>Browser worker queue: <b className="text-text">{jobs.error ? 'خطأ اتصال' : 'متصل'}</b></div><div>Telegram config: <b className="text-text">{telegram.error ? 'غير متصل' : 'متاح'}</b></div><div>البيئة: <b className="text-text">Production</b></div></HealthCard></div><HealthCard title="🧾 آخر Browser Jobs" status={failed === 0}><div className="overflow-x-auto"><table className="w-full min-w-[600px] text-xs"><thead className="text-right text-muted"><tr><th className="p-2">ID</th><th className="p-2">TX</th><th className="p-2">الحالة</th><th className="p-2">الأولوية</th><th className="p-2">التحديث</th></tr></thead><tbody>{jobRows.slice(0, 30).map((row) => <tr key={row.id} className="border-t border-border"><td className="p-2 font-mono">{row.id}</td><td className="p-2 font-mono text-gold">{row.tx_id || '—'}</td><td className="p-2">{row.state}</td><td className="p-2">{row.priority || 0}</td><td className="p-2">{formatAbsoluteDate(row.updated_at || row.next_run_at)}</td></tr>)}</tbody></table></div></HealthCard></div></div></div>
}
