import { useMemo, useState } from 'react'
import Topbar from '../components/Topbar'
import DataTable from '../components/DataTable'
import TablePagination from '../components/TablePagination'
import PaymentMethodBadge from '../components/PaymentMethodBadge'
import { useRealtimeTable } from '../hooks/useRealtimeTable'
import { formatAbsoluteDate, formatMoney, formatNumber } from '../utils/format'

const dateOf = (row) => row.created_utc || row.created_at || row.received_at || row.updated_at
const isOut = (row) => String(row.trx_type || row.sms_category || '').toLowerCase().includes('withdraw') || String(row.trx_type || '').toLowerCase().includes('payout')

export default function HubFinance() {
  const [from, setFrom] = useState(''); const [to, setTo] = useState(''); const [search, setSearch] = useState(''); const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(50)
  const tx = useRealtimeTable({ key: ['hub-finance-tx'], queryFn: async (sb) => sb.from('maven_transactions').select('*').order('created_utc', { ascending: false }).limit(5000), intervalMs: 15000 })
  const sms = useRealtimeTable({ key: ['hub-finance-sms'], queryFn: async (sb) => sb.from('inbound_sms').select('*').order('received_at', { ascending: false }).limit(5000), intervalMs: 15000 })
  const rows = useMemo(() => [...(tx.data || []).map((row) => ({ ...row, source: 'TRX', direction: isOut(row) ? 'out' : 'in' })), ...(sms.data || []).map((row) => ({ ...row, id: `sms-${row.id}`, tx_id: row.trx_id || row.id, source: 'SMS', direction: isOut(row) ? 'out' : 'in', created_utc: row.received_at }))].filter((row) => { const date = String(dateOf(row) || '').slice(0, 10); const term = search.toLowerCase(); const text = [row.tx_id, row.amount, row.sender_name, row.sender_number, row.to_account_number, row.merchant, row.provider, row.source].join(' ').toLowerCase(); return (!from || date >= from) && (!to || date <= to) && (!term || text.includes(term)) }).sort((a, b) => new Date(dateOf(b) || 0) - new Date(dateOf(a) || 0)), [tx.data, sms.data, from, to, search])
  const stats = useMemo(() => rows.reduce((acc, row) => { const amount = Number(row.amount || 0); acc[row.direction] += amount; acc.count += 1; return acc }, { in: 0, out: 0, count: 0 }), [rows])
  const merchants = useMemo(() => { const map = new Map(); rows.forEach((row) => { const key = row.master_merchant || row.merchant || row.merchant_name || 'Unassigned'; const item = map.get(key) || { merchant: key, incoming: 0, outgoing: 0, count: 0 }; item[row.direction === 'out' ? 'outgoing' : 'incoming'] += Number(row.amount || 0); item.count += 1; map.set(key, item) }); return [...map.values()].sort((a, b) => b.incoming - a.incoming) }, [rows])
  const columns = [{ key: 'time', label: 'Time', render: (row) => <span className="text-xs text-muted">{formatAbsoluteDate(dateOf(row))}</span> }, { key: 'direction', label: 'Flow', render: (row) => <span className={row.direction === 'out' ? 'text-danger' : 'text-success'}>{row.direction === 'out' ? '💸 Out' : '💰 In'}</span> }, { key: 'amount', label: 'Amount', render: (row) => <b>{formatMoney(row.amount)}</b> }, { key: 'reference', label: 'TRX / SMS', render: (row) => <span className="font-mono text-gold">{row.tx_id || row.id}</span> }, { key: 'party', label: 'From / To', render: (row) => row.sender_name || row.sender_number || row.to_account_number || row.receiver_number || '—' }, { key: 'merchant', label: 'Merchant', render: (row) => row.master_merchant ? `${row.master_merchant} · ${row.merchant || ''}` : row.merchant || row.merchant_name || '—' }, { key: 'method', label: 'Method', render: (row) => <PaymentMethodBadge value={row.payment_method || row.provider || row.sender_number} /> }, { key: 'status', label: 'Status', render: (row) => row.status || (row.matched ? 'Matched' : 'Received') }]
  const visible = rows.slice((page - 1) * pageSize, page * pageSize)
  return <div className="flex h-full flex-col bg-bg"><Topbar title="💰 Hub Finance" subtitle="Wallet cash flow, reconciled transactions and merchant totals" onRefresh={() => { tx.refresh(); sms.refresh() }} isFetching={tx.isFetching || sms.isFetching} /><div className="flex-1 space-y-5 overflow-y-auto p-4 md:p-6"><div className="mx-auto max-w-[1800px] space-y-5"><div className="flex flex-wrap items-end gap-3 rounded-2xl border border-border bg-card p-4"><Field label="From"><input type="date" value={from} onChange={(e) => { setFrom(e.target.value); setPage(1) }} /></Field><Field label="To"><input type="date" value={to} onChange={(e) => { setTo(e.target.value); setPage(1) }} /></Field><Field label="Search" wide><input value={search} onChange={(e) => { setSearch(e.target.value); setPage(1) }} placeholder="TRX, SMS, phone, wallet, merchant…" /></Field><button onClick={() => { setFrom(''); setTo(''); setSearch(''); setPage(1) }} className="rounded-lg border border-border px-3 py-2 text-sm text-muted hover:text-text">Clear filters</button></div><div className="grid grid-cols-2 gap-3 md:grid-cols-5"><Stat label="Incoming" value={formatMoney(stats.in)} tone="text-success" /><Stat label="Outgoing" value={formatMoney(stats.out)} tone="text-danger" /><Stat label="Net" value={formatMoney(stats.in - stats.out)} tone="text-gold" /><Stat label="Records" value={formatNumber(stats.count)} /><Stat label="Merchants" value={formatNumber(merchants.length)} /></div><section className="rounded-2xl border border-border bg-card p-5"><h2 className="mb-4 font-black text-gold">Merchant finance</h2><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-sm"><thead className="bg-surface text-xs text-muted"><tr>{['Merchant', 'Incoming', 'Outgoing', 'Net', 'Records'].map((label) => <th key={label} className="p-3 text-left">{label}</th>)}</tr></thead><tbody>{merchants.map((row) => <tr key={row.merchant} className="border-t border-border"><td className="p-3 font-bold text-gold">{row.merchant}</td><td className="p-3 text-success">{formatMoney(row.incoming)}</td><td className="p-3 text-danger">{formatMoney(row.outgoing)}</td><td className="p-3 font-bold">{formatMoney(row.incoming - row.outgoing)}</td><td className="p-3">{formatNumber(row.count)}</td></tr>)}</tbody></table>{!merchants.length && <div className="p-8 text-center text-sm text-muted">No merchant finance data.</div>}</div></section><DataTable columns={columns} data={visible} loading={tx.isLoading || sms.isLoading} error={tx.error || sms.error} emptyEmoji="💰" emptyTitle="No finance records" emptySubtitle="Adjust the date range or wait for data." paginated={false} /><TablePagination total={rows.length} page={Math.min(page, Math.max(1, Math.ceil(rows.length / pageSize)))} pageSize={pageSize} onPageChange={setPage} onPageSizeChange={(size) => { setPageSize(size); setPage(1) }} /></div></div></div>
}
function Field({ label, children, wide }) { return <label className={`${wide ? 'min-w-[260px] flex-1' : 'min-w-[150px]'} text-xs text-muted`}>{label}<span className="mt-1 block [&_input]:w-full [&_input]:rounded-lg [&_input]:border [&_input]:border-border [&_input]:bg-surface [&_input]:px-3 [&_input]:py-2 [&_input]:text-sm [&_input]:text-text">{children}</span></label> }
function Stat({ label, value, tone = 'text-gold' }) { return <div className="rounded-xl border border-border bg-card p-4"><div className="text-xs text-muted">{label}</div><div className={`mt-2 truncate text-xl font-black ${tone}`}>{value}</div></div> }
