import { useMemo, useState } from 'react'
import Topbar from '../components/Topbar'
import PaymentMethodBadge from '../components/PaymentMethodBadge'
import { useRealtimeTable } from '../hooks/useRealtimeTable'
import { formatAbsoluteDate, formatMoney, formatNumber } from '../utils/format'

const tabs = [['register', '📒', 'Register'], ['wallets', '👛', 'Wallets'], ['treasury', '📊', 'Treasury'], ['messages', '🔗', 'Messages'], ['transactions', '💳', 'Transactions'], ['import', '📥', 'Import']]

export default function TreasuryHub() {
  const [tab, setTab] = useState('register'); const [direction, setDirection] = useState('in'); const [query, setQuery] = useState(''); const [csv, setCsv] = useState([])
  const wallets = useRealtimeTable({ key: ['hub-wallets'], queryFn: async (sb) => sb.from('v_wallet_financial_summary').select('*').limit(500), intervalMs: 15000 })
  const devices = useRealtimeTable({ key: ['hub-devices'], queryFn: async (sb) => sb.from('wallet_device_map').select('*').limit(500), intervalMs: 30000 })
  const sms = useRealtimeTable({ key: ['hub-sms'], queryFn: async (sb) => sb.from('inbound_sms').select('id,amount,sender_name,sender_number,receiver_number,confirmed_wallet_number,wallet,device_name,received_at,sms_category,consumed_by_tx_id,message').order('received_at', { ascending: false }).limit(500), intervalMs: 10000 })
  const transactions = useRealtimeTable({ key: ['hub-tx'], queryFn: async (sb) => sb.from('maven_transactions').select('tx_id,amount,status,sender_name,sender_number,to_account_number,payment_method,created_utc,updated_at,approved_by').order('tx_id', { ascending: false }).limit(500), intervalMs: 10000 })
  const walletRows = useMemo(() => (wallets.data || []).filter((row) => !query || [row.wallet, row.account, row.wallet_number, row.device, row.providers, row.payment_type].some((value) => String(value || '').toLowerCase().includes(query.toLowerCase()))), [wallets.data, query])
  const txRows = useMemo(() => (transactions.data || []).filter((row) => !query || [row.tx_id, row.amount, row.status, row.sender_name, row.sender_number, row.to_account_number].some((value) => String(value || '').toLowerCase().includes(query.toLowerCase()))), [transactions.data, query])
  const incoming = (sms.data || []).filter((row) => row.sms_category !== 'withdrawal').reduce((sum, row) => sum + Number(row.amount || 0), 0); const outgoing = (sms.data || []).filter((row) => row.sms_category === 'withdrawal').reduce((sum, row) => sum + Number(row.amount || 0), 0)
  function importCsv(file) { if (!file) return; const lines = []; const reader = new FileReader(); reader.onload = () => { String(reader.result).split(/\r?\n/).filter(Boolean).forEach((line) => { const [amount, wallet, counterparty, note] = line.split(','); if (Number(amount)) lines.push({ amount, wallet, counterparty, note }) }); setCsv(lines) }; reader.readAsText(file) }
  return <div className="flex h-full flex-col bg-bg"><Topbar title="OnTarget — Treasury & Wallets" subtitle="Live wallet movement, messages and transactions" onRefresh={() => { wallets.refresh(); devices.refresh(); sms.refresh(); transactions.refresh() }} isFetching={wallets.isFetching || sms.isFetching || transactions.isFetching} /><div className="flex-1 overflow-y-auto p-3 md:p-6"><div className="mx-auto max-w-[1500px] space-y-4"><div className="flex gap-2 overflow-x-auto rounded-2xl border border-border bg-card p-2">{tabs.map(([key, icon, label]) => <button key={key} onClick={() => setTab(key)} className={`min-w-[110px] whitespace-nowrap rounded-xl border px-3 py-2 text-sm font-black ${tab === key ? 'border-gold bg-gold/10 text-gold' : 'border-border text-muted hover:text-text'}`}>{icon} {label}</button>)}</div>{tab === 'register' && <Register direction={direction} setDirection={setDirection} wallets={walletRows} />}{tab === 'wallets' && <Wallets rows={walletRows} devices={devices.data || []} query={query} setQuery={setQuery} />}{tab === 'treasury' && <Treasury incoming={incoming} outgoing={outgoing} wallets={walletRows} />}{tab === 'messages' && <Messages rows={sms.data || []} />}{tab === 'transactions' && <Transactions rows={txRows} />}{tab === 'import' && <Import csv={csv} onFile={importCsv} />}</div></div></div>
}

function Register({ direction, setDirection, wallets }) { return <section className="mx-auto max-w-3xl rounded-2xl border border-border bg-card p-5"><div className="mb-4 flex gap-2"><button onClick={() => setDirection('in')} className={`flex-1 rounded-xl border px-4 py-3 font-black ${direction === 'in' ? 'border-success bg-success/10 text-success' : 'border-border text-muted'}`}>⬇ Incoming</button><button onClick={() => setDirection('out')} className={`flex-1 rounded-xl border px-4 py-3 font-black ${direction === 'out' ? 'border-danger bg-danger/10 text-danger' : 'border-border text-muted'}`}>⬆ Outgoing</button></div><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs text-muted">Amount EGP<input type="number" min="0" placeholder="0.00" className="mt-1 w-full rounded-lg border border-border bg-surface px-3 py-3 text-xl font-mono text-text" /></label><label className="text-xs text-muted">Wallet<select className="mt-1 w-full rounded-lg border border-border bg-surface px-3 py-3 text-text"><option value="">Choose wallet</option>{wallets.map((row) => <option key={row.wallet || row.account} value={row.wallet || row.account}>{row.wallet || row.account}</option>)}</select></label><label className="text-xs text-muted">Counterparty<input placeholder="Merchant / client" className="mt-1 w-full rounded-lg border border-border bg-surface px-3 py-2 text-text" /></label><label className="text-xs text-muted">Occurred at<input type="datetime-local" className="mt-1 w-full rounded-lg border border-border bg-surface px-3 py-2 text-text" /></label></div><button onClick={() => window.location.assign('/wallet-flow')} className="mt-4 w-full rounded-xl bg-gold px-4 py-3 font-black text-bg">Open wallet movement manager</button><p className="mt-3 text-center text-xs text-muted">Ledger editing and SIM management are available in Wallet Flow.</p></section> }
function Wallets({ rows, devices, query, setQuery }) { const deviceMap = new Map(devices.map((row) => [String(row.to_account_number || row.wallet || row.account), row])); return <><div className="flex flex-wrap gap-3"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search wallet or device…" className="min-w-[240px] flex-1 rounded-xl border border-border bg-card px-4 py-3 text-text" /><Stat label="Wallets" value={rows.length} /></div><div className="grid gap-3 md:grid-cols-2">{rows.map((row) => { const number = String(row.wallet || row.account || row.wallet_number || ''); const map = deviceMap.get(number) || {}; const net = Number(row.paid_amt || 0) - Number(row.out_amt || 0); return <div key={number} className="rounded-2xl border border-border bg-card p-4"><div className="flex items-start justify-between gap-3"><div><div className="font-mono font-bold text-gold">{number || '—'}</div><div className="mt-1 text-xs text-muted">{map.device || row.device || 'No device'} · {map.sim_slot ? `SIM ${map.sim_slot}` : 'No SIM'}</div></div><PaymentMethodBadge value={row.providers || row.payment_type || number} /></div><div className="mt-4 grid grid-cols-3 gap-2 text-center text-xs"><div><span className="text-muted">In</span><b className="mt-1 block text-success">{formatMoney(row.paid_amt)}</b></div><div><span className="text-muted">Out</span><b className="mt-1 block text-danger">{formatMoney(row.out_amt)}</b></div><div><span className="text-muted">Net</span><b className={`mt-1 block ${net >= 0 ? 'text-gold' : 'text-danger'}`}>{formatMoney(net)}</b></div></div></div>})}</div></> }
function Treasury({ incoming, outgoing, wallets }) { return <><div className="grid grid-cols-2 gap-3 md:grid-cols-4"><Stat label="Incoming" value={formatMoney(incoming)} tone="text-success" /><Stat label="Outgoing" value={formatMoney(outgoing)} tone="text-danger" /><Stat label="Net" value={formatMoney(incoming - outgoing)} tone="text-gold" /><Stat label="Wallets" value={formatNumber(wallets.length)} /></div><section className="rounded-2xl border border-border bg-card p-5"><h2 className="mb-4 font-black text-gold">Wallet flow</h2>{wallets.slice(0, 20).map((row) => { const number = row.wallet || row.account || row.wallet_number; const inValue = Number(row.paid_amt || 0); const outValue = Number(row.out_amt || 0); const max = Math.max(1, inValue, outValue); return <div key={number} className="mb-3 flex items-center gap-3 text-xs"><span className="w-32 truncate font-mono">{number}</span><div className="flex h-3 flex-1 overflow-hidden rounded-full bg-surface"><i className="bg-success" style={{ width: `${inValue / max * 50}%` }} /><i className="bg-danger" style={{ width: `${outValue / max * 50}%` }} /></div><span className="w-24 text-right font-mono">{formatMoney(inValue - outValue)}</span></div>})}</section></> }
function Messages({ rows }) { const unlinked = rows.filter((row) => !row.consumed_by_tx_id); return <section className="rounded-2xl border border-border bg-card p-4"><h2 className="mb-3 font-black text-gold">Unlinked incoming messages · {unlinked.length}</h2><div className="space-y-2">{unlinked.slice(0, 100).map((row) => <div key={row.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl bg-surface p-3 text-sm"><span className="font-bold">{row.sender_name || row.sender_number || 'Unknown'}</span><span className="font-mono text-gold">{formatMoney(row.amount)}</span><span className="text-xs text-muted">{row.receiver_number || row.confirmed_wallet_number || row.wallet || '—'} · {formatAbsoluteDate(row.received_at)}</span><button onClick={() => window.location.assign('/smslive')} className="rounded-lg border border-gold px-3 py-1 text-xs text-gold">Link</button></div>)}</div>{!unlinked.length && <Empty />}</section> }
function Transactions({ rows }) { return <section className="overflow-x-auto rounded-2xl border border-border bg-card"><table className="w-full min-w-[950px] text-sm"><thead className="bg-surface text-xs text-muted"><tr><th className="p-3 text-left">TX ID</th><th className="p-3 text-left">Amount</th><th className="p-3 text-left">Status</th><th className="p-3 text-left">Sender</th><th className="p-3 text-left">Wallet</th><th className="p-3 text-left">Method</th><th className="p-3 text-left">Time</th></tr></thead><tbody>{rows.map((row) => <tr key={row.tx_id} className="border-t border-border"><td className="p-3 font-mono text-gold">{row.tx_id}</td><td className="p-3 font-bold">{formatMoney(row.amount)}</td><td className="p-3">{row.status}</td><td className="p-3">{row.sender_name || row.sender_number || '—'}</td><td className="p-3 font-mono">{row.to_account_number || '—'}</td><td className="p-3"><PaymentMethodBadge value={row.payment_method || row.sender_number} /></td><td className="p-3 text-xs text-muted">{formatAbsoluteDate(row.updated_at || row.created_utc)}</td></tr>)}</tbody></table>{!rows.length && <Empty />}</section> }
function Import({ csv, onFile }) { return <section className="mx-auto max-w-3xl rounded-2xl border border-border bg-card p-5"><h2 className="mb-2 font-black text-gold">📄 Import CSV</h2><p className="mb-4 text-xs text-muted">Select a CSV to preview amount, wallet, counterparty and note columns.</p><input type="file" accept=".csv,text/csv" onChange={(event) => onFile(event.target.files?.[0])} className="w-full rounded-xl border border-border bg-surface p-3 text-sm text-text" />{csv.length > 0 && <div className="mt-4 space-y-2">{csv.map((row, index) => <div key={index} className="flex justify-between rounded-lg bg-surface p-3 text-sm"><span className="font-mono text-gold">{row.amount}</span><span>{row.wallet || '—'}</span><span>{row.counterparty || '—'}</span></div>)}</div>}</section> }
function Stat({ label, value, tone = 'text-gold' }) { return <div className="rounded-xl border border-border bg-card p-4"><div className="text-xs text-muted">{label}</div><div className={`mt-2 text-xl font-black ${tone}`}>{value}</div></div> }
function Empty() { return <div className="p-10 text-center text-sm text-muted">No data available.</div> }
