import { useEffect, useMemo, useState } from 'react'
import { supabase } from '../lib/supabase'
import { useRealtimeTable } from '../hooks/useRealtimeTable'
import { formatAbsoluteDate, formatNumber } from '../utils/format'
import Topbar from '../components/Topbar'
import DataTable from '../components/DataTable'

async function sha256(value) {
  const bytes = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(value))
  return [...new Uint8Array(bytes)].map((byte) => byte.toString(16).padStart(2, '0')).join('')
}

export default function UsersAdmin() {
  const [form, setForm] = useState({ username: '', display_name: '', password: '', role: 'viewer' }); const [saving, setSaving] = useState(false); const [message, setMessage] = useState('')
  const users = useRealtimeTable({ key: ['panel-users'], queryFn: async (sb) => sb.from('panel_users').select('id, username, display_name, role, active, created_at, last_login_at').order('created_at', { ascending: false }), intervalMs: 15000 })
  const permissions = useRealtimeTable({ key: ['panel-permissions'], queryFn: async (sb) => sb.from('panel_permissions').select('*').order('role', { ascending: true }).order('tab_key', { ascending: true }), intervalMs: 15000 })
  const roles = useRealtimeTable({ key: ['roles'], queryFn: async (sb) => sb.from('roles').select('*').eq('is_active', true).order('name'), intervalMs: 60000 })
  const roleOptions = useMemo(() => [...new Set([...(roles.data || []).map((role) => role.code), ...(users.data || []).map((user) => user.role), 'owner', 'admin', 'operator', 'viewer'].filter(Boolean))], [roles.data, users.data])
  async function createUser(event) { event.preventDefault(); if (!form.username || !form.password) return setMessage('Username and password are required.'); setSaving(true); const password_hash = await sha256(form.password); const { error } = await supabase.from('panel_users').insert({ username: form.username.trim(), display_name: form.display_name.trim() || form.username.trim(), password_hash, role: form.role, active: true }); setSaving(false); if (error) setMessage(error.message); else { setMessage('User created successfully.'); setForm({ username: '', display_name: '', password: '', role: 'viewer' }); users.refresh() } }
  async function togglePermission(row, field) { await supabase.from('panel_permissions').update({ [field]: !row[field] }).eq('role', row.role).eq('tab_key', row.tab_key); permissions.refresh() }
  const userColumns = [{ key: 'username', label: 'Username' }, { key: 'display_name', label: 'Display name' }, { key: 'role', label: 'Role' }, { key: 'active', label: 'Status', render: (row) => row.active ? 'Active' : 'Disabled' }, { key: 'created_at', label: 'Created', render: (row) => formatAbsoluteDate(row.created_at) }, { key: 'last_login_at', label: 'Last login', render: (row) => formatAbsoluteDate(row.last_login_at) }]
  return <div className="flex h-full flex-col bg-bg"><Topbar title="Users, Roles & Permissions" subtitle="RBAC administration" onRefresh={() => { users.refresh(); permissions.refresh(); roles.refresh() }} isFetching={users.isFetching || permissions.isFetching} /><div className="flex-1 space-y-5 overflow-y-auto p-4 md:p-6"><form onSubmit={createUser} className="grid gap-3 rounded-2xl border border-border bg-card p-5 md:grid-cols-5"><input value={form.username} onChange={(e) => setForm({ ...form, username: e.target.value })} placeholder="Username" className="rounded-lg border border-border bg-surface px-3 py-2 text-sm" /><input value={form.display_name} onChange={(e) => setForm({ ...form, display_name: e.target.value })} placeholder="Display name" className="rounded-lg border border-border bg-surface px-3 py-2 text-sm" /><input type="password" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} placeholder="Password" className="rounded-lg border border-border bg-surface px-3 py-2 text-sm" /><select value={form.role} onChange={(e) => setForm({ ...form, role: e.target.value })} className="rounded-lg border border-border bg-surface px-3 py-2 text-sm">{roleOptions.map((role) => <option key={role}>{role}</option>)}</select><button disabled={saving} className="rounded-lg bg-gold px-4 py-2 text-sm font-bold text-white disabled:opacity-50">{saving ? 'Creating...' : 'Create user'}</button>{message && <div className="md:col-span-5 text-sm text-muted">{message}</div>}</form><div className="rounded-2xl border border-border bg-card p-4"><h2 className="mb-3 font-bold">Users ({formatNumber(users.data?.length || 0)})</h2><DataTable columns={userColumns} data={users.data || []} loading={users.isLoading} error={users.error} emptyEmoji="👥" emptyTitle="No users" /></div><div className="rounded-2xl border border-border bg-card p-4"><h2 className="mb-3 font-bold">Role permissions</h2><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-sm"><thead className="bg-surface text-left text-xs text-muted"><tr><th className="px-3 py-3">Role</th><th className="px-3 py-3">Page</th><th className="px-3 py-3">View</th><th className="px-3 py-3">Edit</th></tr></thead><tbody>{(permissions.data || []).map((row) => <tr key={`${row.role}-${row.tab_key}`} className="border-t border-border"><td className="px-3 py-3 font-semibold">{row.role}</td><td className="px-3 py-3">{row.tab_key}</td><td className="px-3 py-3"><input type="checkbox" checked={!!row.can_view} onChange={() => togglePermission(row, 'can_view')} /></td><td className="px-3 py-3"><input type="checkbox" checked={!!row.can_edit} onChange={() => togglePermission(row, 'can_edit')} /></td></tr>)}</tbody></table></div></div></div></div>
}
