import { useEffect, useMemo, useState } from 'react'
import { supabase } from '../lib/supabase'
import { formatAbsoluteDate, formatMoney, formatNumber } from '../utils/format'
import Topbar from '../components/Topbar'
import DataTable from '../components/DataTable'
import Modal from '../components/Modal'

export default function WalletReport() {
  const [wallets, setWallets] = useState([]); const [transactions, setTransactions] = useState([]); const [recipients, setRecipients] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [search, setSearch] = useState(''); const [filter, setFilter] = useState('all'); const [selected, setSelected] = useState(null)
  async function load() {
    setLoading(true); setError('')
    const results = await Promise.all([supabase.from('v_wallet_financial_summary').select('*'), supabase.from('v_wallet_recent_transactions').select('*').limit(500), supabase.from('v_outgoing_top_recipients').select('*').limit(30)])
    const failure = results.find((result) => result.error)
    if (failure) setError(failure.error.message); else { setWallets(results[0].data || []); setTransactions(results[1].data || []); setRecipients(results[2].data || []) }
    setLoading(false)
  }
  useEffect(() => { load() }, [])
  const rows = useMemo(() => (wallets || []).filter((row) => { const term = search.toLowerCase(); const matchesSearch = !term || [row.wallet, row.merchant].some((value) => String(value ?? '').toLowerCase().includes(term)); const sms = Number(row.pct_sms_confirmed || 0); return matchesSearch && (filter === 'all' || (filter === 'high' && sms >= 70) || (filter === 'low' && sms > 0 && sms < 25) || (filter === 'zero' && !Number(row.sms_matched_tx))) }), [wallets, search, filter])
  const stats = useMemo(() => ({ wallets: rows.length, paidTx: rows.reduce((s, r) => s + Number(r.paid_tx || 0), 0), paid: rows.reduce((s, r) => s + Number(r.paid_amt || 0), 0), outgoing: rows.reduce((s, r) => s + Number(r.out_amt || 0), 0), sms: rows.reduce((s, r) => s + Number(r.sms_matched_tx || 0), 0) }), [rows])
  const columns = [{ key: 'wallet', label: 'Wallet' }, { key: 'merchant', label: 'Merchant' }, { key: 'paid_tx', label: 'Paid transactions', render: (r) => formatNumber(r.paid_tx) }, { key: 'paid_amt', label: 'Incoming', render: (r) => formatMoney(r.paid_amt) }, { key: 'out_amt', label: 'Outgoing', render: (r) => formatMoney(r.out_amt) }, { key: 'net_flow', label: 'Net flow', render: (r) => formatMoney(r.net_flow) }, { key: 'success_rate', label: 'Success', render: (r) => `${r.success_rate || 0}%` }, { key: 'pct_sms_confirmed', label: 'SMS match', render: (r) => `${r.pct_sms_confirmed ?? 0}%` }, { key: 'last_active', label: 'Last active', render: (r) => formatAbsoluteDate(r.last_active) }]
  return <div className="flex h-full flex-col bg-bg"><Topbar title="Wallet Financial Report" subtitle="Wallet flow, success and SMS confirmation" onRefresh={load} isFetching={loading} /><div className="flex-1 space-y-5 overflow-y-auto p-4 md:p-6">{error && <div className="rounded-xl border border-danger/30 bg-danger/10 p-4 text-sm text-danger">{error}</div>}<div className="grid grid-cols-2 gap-4 md:grid-cols-5">{[['Wallets', stats.wallets], ['Paid transactions', stats.paidTx], ['Incoming', formatMoney(stats.paid)], ['Outgoing', formatMoney(stats.outgoing)], ['SMS matched', stats.sms]].map(([label, value]) => <div key={label} className="rounded-2xl border border-border bg-card p-4"><div className="text-xs text-muted">{label}</div><div className="mt-2 text-xl font-bold text-gold">{typeof value === 'number' ? formatNumber(value) : value}</div></div>)}</div><div className="flex flex-wrap items-end gap-3 rounded-2xl border border-border bg-card p-4"><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search wallet or merchant..." className="min-w-[240px] flex-1 rounded-lg border border-border bg-surface px-3 py-2 text-sm text-text" /><select value={filter} onChange={(e) => setFilter(e.target.value)} className="rounded-lg border border-border bg-surface px-3 py-2 text-sm text-text"><option value="all">All wallets</option><option value="high">High SMS match</option><option value="low">Low coverage</option><option value="zero">No SMS</option></select></div><DataTable columns={columns} data={rows} loading={loading} error={error ? new Error(error) : null} onRowClick={setSelected} emptyEmoji="👛" emptyTitle="No wallet data" emptySubtitle="Waiting for financial views" /><div className="rounded-2xl border border-border bg-card p-5"><h2 className="mb-4 font-bold text-text">Top outgoing recipients</h2><div className="grid gap-2 md:grid-cols-2">{recipients.map((row) => <div key={row.recipient} className="flex items-center justify-between rounded-lg bg-surface p-3 text-sm"><span className="font-mono">{row.recipient}</span><span className="font-bold text-danger">{formatMoney(row.total_amt)}</span></div>)}</div></div><div className="rounded-2xl border border-border bg-card p-5"><h2 className="mb-4 font-bold text-text">Recent wallet transactions</h2><div className="grid gap-2 md:grid-cols-2">{transactions.slice(0, 20).map((row) => <div key={row.tx_id || row.id} className="flex items-center justify-between rounded-lg bg-surface p-3 text-sm"><span className="font-mono text-gold">{row.tx_id}</span><span>{formatMoney(row.amount)}</span><span className="text-muted">{row.status}</span></div>)}</div></div></div><Modal open={!!selected} onClose={() => setSelected(null)} title="Wallet details">{selected && <pre className="whitespace-pre-wrap break-words rounded-xl border border-border bg-surface p-4 text-sm text-text">{JSON.stringify(selected, null, 2)}</pre>}</Modal></div>
}
