import { useMemo, useState } from 'react'
import { useRealtimeTable } from '../hooks/useRealtimeTable'
import { formatAbsoluteDate, formatMoney } from '../utils/format'
import Topbar from '../components/Topbar'
import PaymentMethodBadge, { paymentMethodMeta } from '../components/PaymentMethodBadge'

function amount(row, ...keys) { for (const key of keys) if (row?.[key] != null) return Number(row[key]) || 0; return 0 }

function Phone({ wallet }) {
  const method = paymentMethodMeta(wallet.provider || wallet.number)
  return <div className="w-[292px] shrink-0 snap-start rounded-[2.4rem] border-[6px] border-slate-700 bg-black p-2 shadow-2xl shadow-black/50"><div className="rounded-[1.9rem] bg-slate-950 px-3 pb-3 pt-2"><div className="mx-auto mb-3 h-1.5 w-20 rounded-full bg-slate-700" /><div className="mb-2 flex items-center justify-between gap-2 rounded-xl bg-slate-900 px-3 py-2"><div className="flex items-center gap-2"><PaymentMethodBadge value={wallet.provider} /></div><span className="h-2 w-2 animate-pulse rounded-full bg-success" /></div><div className="mb-2 flex items-center justify-between gap-2 px-1"><b className="rounded-md bg-gold/15 px-2 py-1 text-xs text-gold">{wallet.device || 'ONT—'}</b><span className="truncate font-mono text-xs font-bold text-red-300">{wallet.number}</span></div><div className="mb-2 text-[10px] text-slate-500">Bank ID: {wallet.bankId || '—'}</div><div className="mb-3 grid grid-cols-2 gap-1 text-[10px]"><div className="rounded-lg bg-emerald-500/10 p-2"><span className="block text-slate-400">داخل اليوم</span><b className="text-emerald-300">{formatMoney(wallet.dailyIn)} ج</b></div><div className="rounded-lg bg-red-500/10 p-2"><span className="block text-slate-400">خارج اليوم</span><b className="text-red-300">{formatMoney(wallet.dailyOut)} ج</b></div><div className="rounded-lg bg-emerald-500/10 p-2"><span className="block text-slate-400">داخل الشهر</span><b className="text-emerald-300">{formatMoney(wallet.monthlyIn)} ج</b></div><div className="rounded-lg bg-red-500/10 p-2"><span className="block text-slate-400">خارج الشهر</span><b className="text-red-300">{formatMoney(wallet.monthlyOut)} ج</b></div></div><div className="h-[300px] space-y-2 overflow-y-auto rounded-xl bg-slate-900 p-2 touch-pan-y">{wallet.messages.length ? wallet.messages.map((row) => <article key={row.id} className="rounded-lg border border-slate-700 bg-slate-800/90 p-2 text-right"><div className="flex items-center justify-between gap-2"><b className="text-sm text-white">{formatMoney(row.amount)} ج</b><span className="text-[10px] text-slate-400">{formatAbsoluteDate(row.received_at)}</span></div><div className="mt-1 truncate text-[11px] text-slate-300">{row.sender_name || row.sender_number || row.receiver_number || 'رسالة واردة'}</div><div className="mt-1 truncate text-[10px] text-slate-400">{row.trx_id || row.trx_reference || row.message || 'SMS'}</div></article>) : <div className="p-6 text-center text-xs text-slate-500">لا توجد رسائل</div>}</div></div></div>
}

export default function WalletMonitor() {
  const [showAll, setShowAll] = useState(false)
  const sms = useRealtimeTable({ key: ['wallet-monitor-wall'], queryFn: async (sb) => sb.from('inbound_sms').select('id,amount,sender_name,sender_number,receiver_number,confirmed_wallet_number,wallet_name,wallet,device_name,sms_category,trx_id,trx_reference,received_at,message').order('received_at', { ascending: false }).limit(500), intervalMs: 10000 })
  const financial = useRealtimeTable({ key: ['wallet-monitor-financial'], queryFn: async (sb) => sb.from('v_wallet_financial_summary').select('*').limit(500), intervalMs: 15000 })
  const devices = useRealtimeTable({ key: ['wallet-monitor-devices'], queryFn: async (sb) => sb.from('wallet_device_map').select('*').order('device').limit(500), intervalMs: 30000 })
  const registry = useRealtimeTable({ key: ['wallet-monitor-registry'], queryFn: async (sb) => sb.from('wallet_registry').select('*').limit(500), intervalMs: 30000 })
  const wallets = useMemo(() => { const map = new Map(); const add = (number, patch) => { if (!number) return; const key = String(number); map.set(key, { number: key, ...map.get(key), ...patch }) }; for (const row of financial.data || []) add(row.wallet || row.account || row.wallet_number || row.to_account_number, { summary: row, provider: row.providers || row.payment_type || row.payment_method, bankId: row.bank_id || row.maven_bank_id || row.bankId || row.bank_name, device: row.device || row.device_name || row.ont_number }); for (const row of devices.data || []) add(row.to_account_number || row.wallet || row.account || row.wallet_number, { device: row.device || row.device_name || row.ont_number, simSlot: row.sim_slot || row.simSlot, bankId: row.bank_id || row.maven_bank_id || row.bankId || row.bank_name, provider: row.payment_type || row.payment_method || row.provider }); for (const row of registry.data || []) add(row.wallet || row.account || row.wallet_number || row.to_account_number, { device: row.device || row.device_name || row.linked_device || row.ont_number, bankId: row.bank_id || row.maven_bank_id || row.bankId || row.bank_name, provider: row.provider || row.payment_type || row.payment_method }); for (const row of sms.data || []) add(row.confirmed_wallet_number || row.wallet || row.receiver_number || row.wallet_name, { messages: [] }); for (const wallet of map.values()) { const summary = wallet.summary || {}; wallet.messages = (sms.data || []).filter((row) => String(row.confirmed_wallet_number || row.wallet || row.receiver_number || row.wallet_name || '') === wallet.number).slice(0, 40); wallet.provider = wallet.provider || wallet.number; wallet.dailyIn = amount(summary, 'paid_today', 'daily_in', 'today_in'); wallet.dailyOut = amount(summary, 'out_today', 'daily_out', 'today_out'); wallet.monthlyIn = amount(summary, 'paid_month', 'monthly_in', 'paid_amt'); wallet.monthlyOut = amount(summary, 'out_month', 'monthly_out', 'out_amt'); } return [...map.values()].sort((a, b) => String(a.device || '').localeCompare(String(b.device || '')) || a.number.localeCompare(b.number)) }, [financial.data, devices.data, registry.data, sms.data])
  const liveWallets = useMemo(() => wallets.filter((w) => w.device && w.bankId), [wallets])
  const visibleWallets = showAll ? wallets : liveWallets
  const hiddenCount = wallets.length - liveWallets.length
  const refresh = () => { sms.refresh(); financial.refresh(); devices.refresh(); registry.refresh() }
  return <div className="flex h-full flex-col bg-bg"><Topbar title="📱 مراقبة المحافظ على الهواتف" subtitle="كل محفظة مرتبطة بالبنك والجهاز والشبكة" onRefresh={refresh} isFetching={sms.isFetching || financial.isFetching} /><div className="flex-1 overflow-y-auto p-4 md:p-6"><div className="mx-auto max-w-[1900px] space-y-5"><div className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-red-500/20 bg-red-500/5 p-4"><div><h1 className="text-xl font-black text-text">📱 Wallet Phone Monitor</h1><p className="mt-1 text-xs text-muted">كل هاتف باسم ONT، شعار الشبكة، Bank ID، وإجمالي الداخل والخارج.</p></div><div className="flex items-center gap-3"><div className="flex rounded-full border border-border bg-surface p-1 text-xs font-bold"><button onClick={() => setShowAll(false)} className={`rounded-full px-3 py-1.5 transition ${!showAll ? 'bg-success text-white' : 'text-muted hover:text-text'}`}>أجهزة نشطة ({liveWallets.length})</button><button onClick={() => setShowAll(true)} className={`rounded-full px-3 py-1.5 transition ${showAll ? 'bg-gold text-bg' : 'text-muted hover:text-text'}`}>عرض الكل ({wallets.length})</button></div><span className="text-xs font-bold text-success">● LIVE · SMS 10s · Banking 30s</span></div></div>{!showAll && hiddenCount > 0 && <div className="rounded-xl border border-gold/30 bg-gold/5 px-4 py-2 text-xs text-gold">مخفي {hiddenCount} محفظة بدون جهاز/بنك مربوط — <button onClick={() => setShowAll(true)} className="font-bold underline underline-offset-2">عرض الكل</button></div>}<div className="flex snap-x snap-mandatory gap-5 overflow-x-auto pb-6 touch-pan-x">{visibleWallets.map((wallet) => <Phone key={wallet.number} wallet={wallet} />)}{!visibleWallets.length && <div className="w-full rounded-2xl border border-border bg-card p-12 text-center text-sm text-muted">{showAll ? 'بانتظار المحافظ المرتبطة...' : 'لا توجد أجهزة بنكية نشطة حالياً'}</div>}</div></div></div></div>
}
