import { useMemo } from 'react'
import { useRealtimeTable } from '../hooks/useRealtimeTable'
import { formatAbsoluteDate, formatMoney } from '../utils/format'
import Topbar from '../components/Topbar'

function Phone({ wallet, rows }) {
  return <div className="w-[270px] shrink-0 snap-start rounded-[2.4rem] border-[6px] border-slate-700 bg-black p-2 shadow-2xl shadow-black/50"><div className="rounded-[1.9rem] bg-slate-950 px-3 pb-3 pt-2"><div className="mx-auto mb-3 h-1.5 w-20 rounded-full bg-slate-700" /><div className="mb-3 flex items-center justify-between rounded-xl bg-red-600 px-3 py-2 text-white"><span className="flex items-center gap-2"><span className="inline-flex h-8 w-8 items-center justify-center rounded-full bg-white text-xs font-black text-red-600">VF</span><span className="text-xs font-black">Vodafone Cash</span></span><span className="h-2 w-2 animate-pulse rounded-full bg-white" /></div><div className="mb-2 truncate px-1 text-center font-mono text-xs font-bold text-red-300">{wallet}</div><div className="h-[360px] space-y-2 overflow-y-auto rounded-xl bg-slate-900 p-2 touch-pan-y">{rows.length ? rows.map((row) => <article key={row.id} className="rounded-lg border border-slate-700 bg-slate-800/90 p-2 text-right"><div className="flex items-center justify-between gap-2"><b className="text-sm text-white">{formatMoney(row.amount)} ج</b><span className="text-[10px] text-slate-400">{formatAbsoluteDate(row.received_at)}</span></div><div className="mt-1 truncate text-[11px] text-slate-300">{row.sender_name || row.sender_number || row.receiver_number || 'رسالة واردة'}</div><div className="mt-1 truncate text-[10px] text-slate-400">{row.trx_id || row.trx_reference || row.message || 'SMS'}</div></article>) : <div className="p-6 text-center text-xs text-slate-500">لا توجد رسائل</div>}</div></div></div>
}

export default function WalletMonitor() {
  const query = useRealtimeTable({ key: ['wallet-monitor-wall'], queryFn: async (sb) => sb.from('inbound_sms').select('id,amount,sender_name,sender_number,receiver_number,confirmed_wallet_number,wallet_name,wallet,trx_id,trx_reference,received_at,message').order('received_at', { ascending: false }).limit(250), intervalMs: 10000 })
  const wallets = useMemo(() => { const grouped = new Map(); for (const row of query.data || []) { const wallet = row.confirmed_wallet_number || row.wallet || row.receiver_number || row.wallet_name || 'محفظة غير محددة'; if (!grouped.has(wallet)) grouped.set(wallet, []); grouped.get(wallet).push(row) } return [...grouped.entries()] }, [query.data])
  return <div className="flex h-full flex-col bg-bg"><Topbar title="📱 مراقبة المحافظ على الهواتف" subtitle="Vodafone Cash · رسائل SMS حية لكل محفظة" onRefresh={query.refresh} isFetching={query.isFetching} /><div className="flex-1 overflow-y-auto p-4 md:p-6"><div className="mx-auto max-w-[1800px] space-y-5"><div className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-red-500/20 bg-red-500/5 p-4"><div><h1 className="text-xl font-black text-text">📱 Wallet Phone Monitor</h1><p className="mt-1 text-xs text-muted">اسحب يمين/يسار بين الهواتف، واسحب داخل كل هاتف لمراجعة الرسائل.</p></div><span className="text-xs font-bold text-success">● LIVE · تحديث كل 10 ثواني</span></div><div className="flex snap-x snap-mandatory gap-5 overflow-x-auto pb-6 touch-pan-x">{wallets.map(([wallet, rows]) => <Phone key={wallet} wallet={wallet} rows={rows.slice(0, 30)} />)}{!wallets.length && <div className="w-full rounded-2xl border border-border bg-card p-12 text-center text-sm text-muted">بانتظار بيانات المحافظ...</div>}</div></div></div></div>
}
